name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - 'nightly'
          - '~1.9.0-0'
          - '~1.8.0-0'
        julia-arch:
          - x64
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest
      - name: "limit OpenMP threads"
        if: runner.os == 'macOS'
        # restrict number of openMP threads on macOS due to oversubscription
        run: echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
      - name: "debug stuff1"
        if: runner.os == 'macOS'
        run: |
          top -l 2 -u -n 20
          sudo mdutil -a -i off
          sleep 60
          sudo killall -9 mds_stores
          sleep 60
          top -l 2 -u -n 20
      - name: "debug stuff2"
        run: julia -e 'using InteractiveUtils; versioninfo(verbose=true)'
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
      - name: "debug stuff3"
        if: runner.os == 'macOS'
        run: |
          top -l 2 -u -n 20
      - name: "Process code coverage"
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,experimental
      - name: "Upload coverage data to Codecov"
        continue-on-error: true
        uses: codecov/codecov-action@v3
